version: '{build}'
clone_depth: 1
stack: node 8

image:
  - Ubuntu
  - Visual Studio 2017

branches:
  only:
    - master
    - dev

environment:
  ApiKey:
    secure: SeomICfFXAQobyK5uMGeAhb0uljBxicG4Z56pWxWCXA=
  JobToWait: 'Image: Ubuntu'
  FileName: 'date.text'

configuration:
  - Release

init:
  - git config --global core.autocrlf true

install:
- ps: |
  if ($env:APPVEYOR_JOB_NAME -eq $env:JobToWait)
  {
      Get-Date > $env:FileName
      Push-AppveyorArtifact ./$env:FileName
  }

- ps: |
  Import-module ./test.ps1 -Force

  if ($env:APPVEYOR_JOB_NAME -ne $env:JobToWait) 
  {
      Start-ArtifactDownload($env:JobToWait, $env:FileName, $env:ApiKey)
  }

build: off
test: off

